# Create a secret (Store data in encoded format)
# kubectl create secret generic <secret_name> --from-literal=<key1>=<value1> --from-literal=<key2>=<value2>
# kubectl create secret generic <secret_name> --from-file=<file_path>

# List of secrets
# kubectl get secrets

# Store value in encoded format
# echo -n <value> | base64

# Decode encoded value
# echo -n <value> | base64 --decode

apiVersion: v1
kind: Secret
metadata:
  name: mysecret
# type: Opaque
data:
  password: dmlrYXNo

# Create this secret
# kubectl create -f credentials.yml

# Describe secrets
# kubectl describe secrets <secret_name>

---
# Secrets with PODS

apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    envFrom:
      - secretRef:
          name: secret-name
    env:
      - name: env-name
        valueFrom:
          secretKeyRef:
            name: secret-name
            key: secret-key

---
# Secrets with Volumes

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity:
    storage: "128Mi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2
  volumes:
    - name: secret-volume-name
      secret:
        secretName: secret-name

# NOTE:
#   - Secrets are not encrypted, it's only encoded
#   - Do not check-in secret objects to SCM along wiht code
#   - Secrets are not encrypted in ETCD
#   - Enable encryption at rest
#   - Anyone able to create pods/deployments in the same namespace can access the secret
#   - Configure least-privilege access to Secrets - Role Base Access
#   - Consider third-party secrets store providers AWS Provider, Azure Provider, GCP Provider, Vault Provider


# Remember that secrets encode data in base64 format. Anyone with the base64 encoded secret can easily decode it. As such the secrets can be considered as not very safe.

# The concept of safety of the Secrets is a bit confusing in Kubernetes. The kubernetes documentation page and a lot of blogs out there refer to secrets as a "safer option" to store sensitive data. They are safer than storing in plain text as they reduce the risk of accidentally exposing passwords and other sensitive data. In my opinion it's not the secret itself that is safe, it is the practices around it. 

# Secrets are not encrypted, so it is not safer in that sense. However, some best practices around using secrets make it safer. As in best practices like:

# Not checking-in secret object definition files to source code repositories.

# Enabling Encryption at Rest for Secrets so they are stored encrypted in ETCD. 



# Also the way kubernetes handles secrets. Such as:

# A secret is only sent to a node if a pod on that node requires it.

# Kubelet stores the secret into a tmpfs so that the secret is not written to disk storage.

# Once the Pod that depends on the secret is deleted, kubelet will delete its local copy of the secret data as well.

# Read about the protections and risks of using secrets here



# Having said that, there are other better ways of handling sensitive data like passwords in Kubernetes, such as using tools like Helm Secrets, HashiCorp Vault. I hope to make a lecture on these in the future.