apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.14.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000


# Create a deployemnt
# kubectl create -f deployment.yml

# See the list of deployments
# kubectl get deployments

# Deployment automatic create replicaset
# kubectl get replicaset

# Deployment replicaset create pods
# kubectl get pods

# List all the created items (pods, replicaset, deployment, services etc)
# kubectl get all

# Modify and apply new things in created deployment
# kubectl apply -f deployment.yml


# Delete deployment
# kubectl delete deployment <deployment-name>