# List pods with namespce
# kubectl get pods --namespace=<namespace-name>

# Create a pod with name space
# kubectl create -f pod-def.yml --namespace=<namespace-name>
# Or specify namespace in pod-def.yml file in metadata section

# apiVersion: v1

# kind: Pod

# metadata:
#   name: nginx-pod
#   namespace: dev-space
#   labels:
#     app: nginx

# spec:
#   containers:
#   - name: nginx-container
#     image: nginx:1.14.2
#     resources:
#       limits:
#         memory: "128Mi"
#         cpu: "500m"
#     ports:
#       - containerPort: 80

---
# Create a namespace
apiVersion: v1
kind: Namespace
metadata:
  name: dev-space

# Create a namespace
# kubectl create -f namespaces.yml
# Or
# kubectl create namespace <namespace-name>

# List of namespaces
# kubectl get namespaces

# Delete namespace
# kubectl delete namespaces <namespace-name>

# Change permanantly namespace
# kubectl config set-context $(kubectl config current-contex) --namespace=<namespace-name>

# List data from all namespaces
# kubectl get pods --all-namespaces

---
# Resource Quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: dev

spec:
  hard:
    pods: "10"
    requuests.cpu: "4"
    requests.memory: 5Gi
    limits.cpu: "10"
    limits.memory: 10Gi

# Create a resourcequota
# kubectl create -f resourcequota.yml

# List of resourcequota
# kubectl get resourcequota