apiVersion: v1

kind: Pod

metadata:
  name: nginx-pod
  labels:
    app: nginx
    # container: container-name
    # location: India

spec:
  # selector:
  #   matchLabels:
  #     app: nginx
  # replicas: 2 # tells deployment to run 2 pods matching the template
  # template:
  #   metadata:
  #     labels:
  #       app: nginx
  containers:
  - name: nginx-container
    image: nginx:1.14.2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  # - name: backend-redis
  #   image: redis
  #   resources:
  #     limits:
  #       memory: "10Mi"
  #       cpu: "50m"
